### ISSUE TITLE
Kafka Course > Quickstart scenario

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#1]
Implement https://kafka.apache.org/quickstart

Scenario : https://www.katacoda.com/glialabs/courses/kafka/kafka-quickstart

**Comment by adriens** [comment]
Not sure we have to keep the Stream part in this course...

**Comment by HakumenNC** [comment]
Agree to separate stream and connect parts, but it can be teasing on conclusion of this course.
