### ISSUE TITLE
New course request > [PostgreSQL]

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#11]
# Prerequisites

- [x] I have checked that this course does not already exist on your Katacoda organization
- [x] Target course name : `PostgreSQL`
- [x] Short motivation for this course creation : Postgres is widely used, still some of its core features are underestimated os unused

# Motivation

Because it could help me to better :

- Spread best practices
- Share knwoledge about psql performance and tools

# Scenario candidate

- Please implement a scenario dedicated to paritioning and its impact on bloat and performances

**Comment by adriens** [comment]
Course created see https://www.katacoda.com/glialabs/courses/postgresql

**Comment by adriens** [comment]
Remains to put the scenario

**Comment by adriens** [comment]
Move this one https://www.katacoda.com/rastadidi/courses/psql-trick/purge-partitions

**Comment by adriens** [comment]
Bitly url : http://bit.ly/3qLdS2p

![qr-code(9)](https://user-images.githubusercontent.com/5235127/108773237-24fb2780-75b2-11eb-9f2b-f95b71585859.png)

**Comment by adriens** [comment]
Added partitioning overlay @HakumenNC ✔️

**Comment by adriens** [comment]
Ppt mis à jour

**Comment by adriens** [comment]
Si good pour toi @HakumenNC , tu peux fermer l'issue 🙏

**Comment by adriens** [comment]
![Katacoda](https://user-images.githubusercontent.com/5235127/108776091-01d27700-75b6-11eb-9209-0663a7a3561c.png)

**Comment by adriens** [comment]
Used as example for #19

**Comment by HakumenNC** [comment]
All green, vaccumator strike again! ✔️

**Comment by adriens** [comment]
LOOOOOOL, ou jst found the easter egg bro' 😆
