### ISSUE TITLE
Corrections & améliorations session 2 GLIA

### ISSUE THREAD

**Issue by HakumenNC** [adriens/katacoda-glia-labs#14]
! Utiliser les fichiers de la repo !

* Step Start the broker
  * Clone repo
  * `less` sur docker-compose.yml

* Step 3
  * unzip, confirmation (ajouter un `-y`)
  * Favoriser `curl` pour récupération de status

* Step UseCase :
  * Tronquer la stacktrace

* Step Produce data :
  * Ajouter timestamp
  * Tri décroissant

* Step 6 :
  * Ajouter select SQL 

* Step 8 (nouveau) :
  * Cas traitement coté SID
  * Ajout timestamp

* Ajouter Finish
  * Ajouter liens

**Comment by HakumenNC** [comment]
Done ✔️

**Comment by adriens** [comment]
gaffe à `less` : ça ne rend pas la main. Un `cat` peut être plus intéressant pour rendre le fil du cours plus fluide
