### ISSUE TITLE
Kafka connect > bitly et QrCode

### ISSUE THREAD

**Issue by HakumenNC** [adriens/katacoda-glia-labs#15]
Ajout liens bitly et qrcode (?)

**Comment by adriens** [comment]
http://bit.ly/3k4d3z9


![KataCoda-kafka-connect](https://user-images.githubusercontent.com/5235127/108463641-df4d0f00-72d2-11eb-98f7-1d6f7d17b310.png)

**Comment by adriens** [comment]
A toi de reviewer @HakumenNC

**Comment by HakumenNC** [comment]
All good, thanks!

**Comment by adriens** [comment]
👍
