### ISSUE TITLE
Scenario enhancement > Kafka Connect

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#16]
# New Dedicated step : Final table Scenario : complete batch implementation

- create table bi_table table as select * from landing_table where  1=0;
- stop kafka_connect
- send messages to kafka
- insert into bi_table select * from landing_table
- truncate landing_table -- no bloat
- vacuum full analyze landing table - -- remove removable space
- restart k-connect
- select * from landing_table order by timestamp desc

Mettre le lien vers la scenario Katacoda bu bloat

# New Dedicated step : ressources

In a dedicated step, resources : 

- bloat katacoda link
- Kafka connect home page
- schemaresgirty homepage
- confluent images homepage
- ...

**Comment by HakumenNC** [comment]
Done ✔️ in 4c3a362ca0f315ce128aa1f5dac725d23997ee6b

**Comment by adriens** [comment]
Ce scénario est vraiment violent 🥇
