### ISSUE TITLE
Create new scenario [SDKMAN!] in [DevOPS tools] 

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#30]
# Requirements

- [x] I have checked that such a scenario does not already exist in the target course
- [x] Existing course name : `DevOPS Tools`
- [x] Requested Scenario name : `SDKMAN!`

# Optional

You can add some resources you like on this topic, links or videos you appreciate and which could help during scenarion implementation

**Comment by adriens** [comment]
Review for you @HakumenNC 🙏

**Comment by HakumenNC** [comment]
All good ! ✔️

**Comment by adriens** [comment]
Thanks bro'
