### ISSUE TITLE
Create new scenario [ftp with lftp] in [DevOps tools] 

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#32]
# Requirements

- [x] I have checked that such a scenario does not already exist in the target course
- [x] Existing course name : `DevOPs Tools`
- [x] Requested Scenario name : `Ftp and lftp operations`
- [x] Explain your motivation to get this new scenario _lftp is a great tool is desserves it_

**Comment by adriens** [comment]
https://www.katacoda.com/glialabs/courses/devops-tools/lftp-quickstart

**Comment by adriens** [comment]
Next step : testing it

**Comment by adriens** [comment]
Latest tests and evols have been made.
Ready for review @HakumenNC

**Comment by HakumenNC** [comment]
All good ✔️ , especially the bookmarks part, very interesting

**Comment by adriens** [comment]
👏
