### ISSUE TITLE
Create new scenario [Kafka Connect] in [Kafka] 

### ISSUE THREAD

**Issue by adriens** [adriens/katacoda-glia-labs#4]
# Requirements

- [x] I have checked that such a scenario does not already exist in the target course
- [x] Existing course name : `Kafka`
- [x] Requested Scenario name : `Kafka Connect : send data from Kafka to PostgreSQL`
- [x] This feature help perform efficient integrations and save a lot of time : it should require configuration instead of developement

# Optional

[Confluent wikis](https://docs.confluent.io/platform/current/connect/index.html)

**Comment by adriens** [comment]
Code being reviewed last week with @HakumenNC

**Comment by HakumenNC** [comment]
Done in commit : 8e0fdbcb5f4458b59a5ec4017f34ee100bc12043
